### ISSUE TITLE
Cursor does not select words after triggered

### ISSUE THREAD

**Issue by eorroe** [spywhere/SelectExact#3]
Without this plugin I was able to do the following:

`|` (cursor)

```
|hello |world
```

Hit ctrl+d which would end up selecting both words, now having select exact run on `ctrl+d` the above doesn't work

**Comment by spywhere** [comment]
The plugin does not involve any Sublime Text command and also the default key binding does not override the `Ctrl+D` so I don't think the plugin has changed any functionality of the Sublime Text's default behaviour (except the one that use `Ctrl+Shift+D`).

**Comment by eorroe** [comment]
I have:

``` JSON
{
        "keys": ["ctrl+d"],
        "command": "select_exact_match"
    }
```

because I prefer to replace the original with `select_exact_match`

but using `select_exact_match` I can't do what I explained above

**Comment by spywhere** [comment]
That's expectable. The default Sublime Text's behaviour would be override. However, I now got your point of what's going on with the plugin and that's happen to me also.

To confirm the case, can you try causing that to happen again and told me how many times have you pressed the key?

**Comment by eorroe** [comment]
Multiple times still same result

**Comment by spywhere** [comment]
Sorry, I means how many times you have to press the key until it select both words.

**Comment by eorroe** [comment]
It never does with the plugin enabled, that's the point, without the plugin once

**Comment by spywhere** [comment]
Ok, I will try fixing this but that would stop the plugin (press the key again will do nothing) after the selections since the selections are all different which plugin can't distinguish in order to select the next occurrence.

**Comment by eorroe** [comment]
Without plugin this is how it works:

Place 1st cursor (in between `console`):

``` JS
con|sole.log(arg);
console.log(arg);
console.log(arg);
```

Place 2nd cursor (in between `log`):

``` JS
con|sole.log(arg);
console.lo|g(arg);
console.log(arg);
```

Press again it will select the next `log`

Place 2nd cursor (in between `log`):

``` JS
con|sole.log(arg);
console.lo|g(arg);
console.log(arg); // it'll select this log
```

So all you have to do is when there are two cursors match exactly `log`:

``` JS
con|sole.log(arg);
console.lo|g(arg);
console.log(arg);
```

**Comment by spywhere** [comment]
Alright, I have release a new version. This should be fixed in v0.1.1.

**Comment by eorroe** [comment]
You did it with the first select, it should select the text that is within the cursor not just leave the cursor there, if you want I'll make a gif or something tomorrow to show you

**Comment by spywhere** [comment]
Isn't this correct?

![untitled](https://cloud.githubusercontent.com/assets/1087399/12938537/a406e9c2-cfe7-11e5-92c0-165307b40fbb.gif)

**Comment by eorroe** [comment]
Well yes that (which isn't working for me) and also without you actually selecting the whole thing, just having the cursor in between running `select_exact_match` should select both

**NVM JUST UPDATED THE PACKAGE ITS WORKING THANKS**

**Comment by spywhere** [comment]
Yup, placing cursor in between the word also select as if the cursor is place in front of it. If you depend on Package Control installation, new version of SelectExact should be updated automatically within 6 hours. Or you could open the command palette and choose to upgrade the package manually.

**Comment by eorroe** [comment]
Um one other thing if I start selecting from the last instance it doesn't continue from the top

```
hello
hello
|hello
```

Will only select the last one

**Comment by spywhere** [comment]
No, the plugin should select the first one on the next occurrence.

**Comment by eorroe** [comment]
Nvm I'm wrong the selection is different I had:

```
arguments
arguments
|arguments[0]
```

and it only selected the last

but what doesn't work is like `(`, `{` etc

and wait what do you mean, by your last comment

**Comment by spywhere** [comment]
I means...

![untitledxxx](https://cloud.githubusercontent.com/assets/1087399/12938897/ff58611c-cfeb-11e5-933d-4e40484bd02e.gif)

**Comment by eorroe** [comment]
To be exact I have this:

``` JS
self.log = function() {
    if (arguments.length > 1) {
        console.log(arguments);
    } else {
        console.log(arguments[0]);
    }
}
```

it doesn't work on that for some reason

The algorithim is pretty weird sometimes it works sometimes it doesn't

**Comment by spywhere** [comment]
Here. But I pretty sure of what you have experience... I will try fix that

![untitled](https://cloud.githubusercontent.com/assets/1087399/12938925/582744f2-cfec-11e5-8836-7e12b8922cc3.gif)

**Comment by eorroe** [comment]
Alright thanks, @eorroe me when you do plz

**Comment by eorroe** [comment]
What do you make your gifs with so quick by the way?

**Comment by eorroe** [comment]
Weird, try saving that untitled file, and you'll see it doesn't work anymore

**Comment by spywhere** [comment]
I use [licecap](http://www.cockos.com/licecap/). It's free and open source :)
